### ISSUE TITLE
qt5/binding file is missing

### ISSUE THREAD

**Issue by codenoid** [Papierkorb/qt5.cr#1]
```
   1 require "./qt5/version"
   2 require "./qt5/glue"
   3 require "./qt5/point"
   4 require "./qt5/binding" # missing
   5 require "./qt5/*"
```

```
ayam:trypapierqt ruby$ cd lib/qt5/src/qt5
Oderlo-pro:qt5 ruby$ tree
.
├── application.cr
├── glue.cr
├── layout.cr
├── object.cr
├── painter.cr
├── point.cr
└── version.cr
```

**Comment by Papierkorb** [comment]
That file is not missing. It's only distributed in the `x-ready-to-use` branches. `ext/qt_binding.cpp` and `src/qt5/binding.cr` are huge files (Around 50k lines combined atm), and are 100% generated.

The non `x-ready-to-use` branches are for development on the bindings themselves, at which point I expect you to run a full installation of `bindgen` too to generate the bindings yourself.  That doesn't prevent you from copying these files over from the `x-ready-to-use` branch of course, but it's not what I recommend: It only allows you to work on the `*.cr` files, but not modify `qt.yml` in any shape or form.

**Comment by codenoid** [comment]
is this missing or what ?

```
Oderlo-pro:trypapierqt ruby$ crystal build hello.cr
clang: error: no such file or directory: '/Users/ruby/Documents/app/desktop/trypapierqt/lib/qt5/src/qt5/../../ext/binding.a'
```

**Comment by RX14** [comment]
You should tag a 0.1.0 release on a ready to use branch and include that in the readme.

**Comment by Papierkorb** [comment]
This being a TechPreview, there are sometimes huge changes hourly. Versioning doesn't make much sense until I can somewhat guarantee to have something I could semantically version against. To start anything, you'll want to use the ready-to-use branch which is synchronized with `master`.

Actual versioning will start to make sense when this enters a Beta phase.

**Comment by RX14** [comment]
Given 0.x.x has no meaning I usually just start at 0.1.0 and release minors quite regularly.
