### ISSUE TITLE
Add support for 5.11 and above

### ISSUE THREAD

**Issue by repomaa** [Papierkorb/qt5.cr#20]
5.11 is the current version on arch at least which is why it won't build atm.

**Comment by shayneoneill** [comment]
Not sure if its related, but the File.each_line(blah) semantics in generate_bindings need to be updated to something like
```
File.open(blah) do |file|
   file.each_line etc etc
end
```
Theres probably more, but thats where I'm at so far.

**Comment by shayneoneill** [comment]
I think this project has been abandoned :(

**Comment by nogweii** [comment]
[@ZaWertun's fork](https://github.com/ZaWertun/qt5.cr) has been updated to include 5.11 and 5.12.

**Comment by Serkan-devel** [comment]
is this repo still maintained?

**Comment by shayneoneill** [comment]
I don't think so , but that fork looks promising.

Its a bloody shame if it has been abandoned. QML + Crystal would be an amazing combo.

**Comment by docelic** [comment]
It appears that @ZaWertun who also contributed to https://github.com/Papierkorb/bindgen has been able to get it working with 5.13 as well.

Also, maintenance of qt5.cr is now active again - please see https://github.com/Papierkorb/qt5.cr/issues/29 .

I will keep this ticket open simply as a way to track progress on actually updating it to 5.11 (before moving onto newer versions). Currently the last version mentioned in `support/generate_bindings.cr` for which the source archive exists at https://download.qt.io/archive/qt/ is 5.9.

**Comment by docelic** [comment]
Definitions for Qt up to and including 5.13 are now in `support/generate_bindings.cr`. Support for 5.11 is disabled, though, because it is not present in https://download.qt.io/archive/qt/ , but 5.12 and 5.13 are.

**Comment by shayneoneill** [comment]
Any idea if/when 5.14 will be there?

**Comment by docelic** [comment]
I see .15 available as well. Will try both during today, at least so that we have initial feedback whether it generates or not.

**Comment by docelic** [comment]
#31
