### ISSUE TITLE
Get latest version of Qt5

### ISSUE THREAD

**Issue by acoolstraw** [Papierkorb/qt5.cr#28]
Currently, qt5.cr downloads and attempts to generate bindings for outdated versions of Qt5.

Should be as easy as changing the download link, but keep in mind that the URL structure has changed. I believe I've committed the changes to my fork of qt5.cr, but not entirely sure

**Comment by acoolstraw** [comment]
no I haven't

**Comment by docelic** [comment]
@acoolstraw yeah if you look at https://download.qt.io/archive/qt/ , it appears that the directory structure is still the same, but many of the releases pre-configured in `support/generate_bindings.cr` are not found there.

One that is found, though, is 5.9 and it works without changing any paths. I am going to use it to try reproduce a build that worked in the past before moving onto newer versions.

**Comment by docelic** [comment]
For reference, the file path pattern has changed beginning with 5.12.0, from `qt-everywhere-opensource-src-#{@name}.0.tar.xz` to `qt-everywhere-src-#{@name}.0.tar.xz`

**Comment by docelic** [comment]
I've merged @ZaWertun's changes for Qt up to and including 5.13, and versions which are no longer available at https://download.qt.io/archive/qt/ are still in the list, but are now disabled.
Also, the support for choosing the old or new path based on version has been added.
